name: Mirror Markdown to Gist

on:
  workflow_call:
    inputs:
      file_path:
        description: 'Path to the markdown file (.md) in the repository to mirror to gist'
        required: true
        type: string
    secrets:
      GH_PAT_PROFESSOR_SERP:
        required: true

jobs:
  mirror-to-gist:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Validate and read markdown file
        id: read_file
        shell: bash
        run: |
          # Check if file exists
          if [ ! -f "${{ inputs.file_path }}" ]; then
            echo "Error: File not found at ${{ inputs.file_path }}"
            exit 1
          fi
          
          # Check if file is markdown
          if [[ ! "${{ inputs.file_path }}" =~ \.md$ ]]; then
            echo "Error: File must be a markdown file (.md)"
            exit 1
          fi
          
          # Read the file content (raw, not JSON-encoded yet)
          FILE_CONTENT=$(cat "${{ inputs.file_path }}")
          echo "file_content<<EOF" >> $GITHUB_OUTPUT
          echo "$FILE_CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          # Get the filename
          FILENAME=$(basename "${{ inputs.file_path }}")
          echo "filename=$FILENAME" >> $GITHUB_OUTPUT
          
          # Extract title from frontmatter if it exists
          DESCRIPTION=""
          if head -n 1 "${{ inputs.file_path }}" | grep -q "^---"; then
            # File has frontmatter, extract title
            FRONTMATTER=$(sed -n '/^---$/,/^---$/p' "${{ inputs.file_path }}" | sed '1d;$d')
            DESCRIPTION=$(echo "$FRONTMATTER" | grep "^title:" | sed 's/^title:[[:space:]]*//' | sed 's/^["'\'']//;s/["'\'']$//')
          fi
          
          # Use default description if no title found in frontmatter
          if [ -z "$DESCRIPTION" ]; then
            DESCRIPTION="Mirror of ${{ inputs.file_path }} from ${{ github.repository }}"
          fi
          
          echo "description=$DESCRIPTION" >> $GITHUB_OUTPUT
          
      - name: Create or update gist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT_PROFESSOR_SERP }}
        shell: bash
        run: |
          # Prepare the gist payload
          FILENAME="${{ steps.read_file.outputs.filename }}"
          DESCRIPTION="${{ steps.read_file.outputs.description }}"
          
          # Read the raw file content and create JSON payload
          cat "${{ inputs.file_path }}" | jq -Rs --arg desc "$DESCRIPTION" --arg fname "$FILENAME" \
            '{description: $desc, public: true, files: {($fname): {content: .}}}' > payload.json
          
          # Create the gist using GitHub API
          RESPONSE=$(curl -s -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/gists \
            -d @payload.json)
          
          # Extract and display the gist URL
          GIST_URL=$(echo "$RESPONSE" | jq -r '.html_url')
          
          if [ "$GIST_URL" = "null" ] || [ -z "$GIST_URL" ]; then
            echo "Error creating gist:"
            echo "$RESPONSE" | jq .
            exit 1
          fi
          
          echo "✅ Gist created successfully!"
          echo "📎 Gist URL: $GIST_URL"
          echo "📁 Mirrored file: ${{ inputs.file_path }}"